/*
 * Generate server/db/rows.ts from the live schema.
 *
 * One interface per table in the public schema, column for column, with the
 * TypeScript type pg hands back for each Postgres type and `| null` where the
 * column is nullable. Run against a migrated database:
 *
 *   node server/db/generate-rows.ts            # writes server/db/rows.ts
 *   node server/db/generate-rows.ts out.ts     # writes elsewhere (the gate)
 *
 * `make rows` does the first against this checkout's database, and
 * scripts/check-rows.sh regenerates into a temporary file and diffs, in the
 * CI smoke job (which already has a migrated Postgres), so a migration that
 * renames or retypes a column fails the build until the committed types —
 * and therefore every query typed by them — are brought up to date.
 *
 * Deliberately a hundred lines rather than a dependency: kysely-codegen and
 * kanel each want a peer (kysely, prettier) this repository has no other
 * use for, and the mapping below is the whole of what they would do here.
 */
import fs from "node:fs";
import path from "node:path";
import { pool } from "./database.ts";

interface Column {
  table_name: string;
  column_name: string;
  data_type: string;
  is_nullable: "YES" | "NO";
  ordinal_position: number;
}

/* What pg's default type parsers produce for each Postgres type. */
const TS_TYPES: Record<string, string> = {
  integer: "number",
  smallint: "number",
  real: "number",
  "double precision": "number",
  boolean: "boolean",
  text: "string",
  "character varying": "string",
  character: "string",
  uuid: "string",
  json: "unknown",
  jsonb: "unknown",
  date: "Date",
  "timestamp with time zone": "Date",
  "timestamp without time zone": "Date",
  // pg returns these as strings to avoid losing precision.
  bigint: "string",
  numeric: "string",
};

/* users -> UserRow, profile_photos -> ProfilePhotoRow, external_identities
 * -> ExternalIdentityRow. */
const interfaceName = (table: string): string => {
  const singular = table.endsWith("ies")
    ? `${table.slice(0, -3)}y`
    : table.endsWith("s")
      ? table.slice(0, -1)
      : table;
  const pascal = singular
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
  return `${pascal}Row`;
};

export async function generateRows(): Promise<string> {
  const { rows } = await pool.query<Column>(
    `SELECT table_name, column_name, data_type, is_nullable, ordinal_position
       FROM information_schema.columns
      WHERE table_schema = 'public'
      ORDER BY table_name, ordinal_position`,
  );

  const tables = new Map<string, Column[]>();
  for (const column of rows) {
    const list = tables.get(column.table_name) ?? [];
    list.push(column);
    tables.set(column.table_name, list);
  }

  const lines: string[] = [
    "/*",
    " * The tables, as pg hands their rows back.",
    " *",
    " * GENERATED by server/db/generate-rows.ts from the live schema; do not",
    " * edit. `make rows` regenerates it, and scripts/check-rows.sh fails CI",
    " * when it is stale. Shapes derived from these (joins, aggregates) live",
    " * in server/db/shapes.ts.",
    " */",
    "",
  ];

  for (const [table, columns] of tables) {
    lines.push(`/* ${table} */`, `export interface ${interfaceName(table)} {`);
    for (const column of columns) {
      const base = TS_TYPES[column.data_type];
      if (!base) {
        throw new Error(
          `no TypeScript type for ${table}.${column.column_name} (${column.data_type}); add it to TS_TYPES`,
        );
      }
      const type = column.is_nullable === "YES" ? `${base} | null` : base;
      lines.push(`  ${column.column_name}: ${type};`);
    }
    lines.push("}", "");
  }

  return lines.join("\n");
}

if (import.meta.main) {
  const out = process.argv[2] ?? path.join(import.meta.dirname, "rows.ts");
  generateRows()
    .then((text) => {
      fs.writeFileSync(out, text);
      console.log(`wrote ${out}`);
      return pool.end();
    })
    .then(() => process.exit(0))
    .catch((err: unknown) => {
      console.error(err instanceof Error ? err.message : err);
      process.exit(1);
    });
}
