/*
 * The tables, as pg hands their rows back.
 *
 * GENERATED by server/db/generate-rows.ts from the live schema; do not
 * edit. `make rows` regenerates it, and scripts/check-rows.sh fails CI
 * when it is stale. Shapes derived from these (joins, aggregates) live
 * in server/db/shapes.ts.
 */

/* external_identities */
export interface ExternalIdentityRow {
  user_id: number;
  issuer: string;
  subject: string;
  provider: string | null;
  created_at: Date;
}

/* friends */
export interface FriendRow {
  user1_id: number;
  user2_id: number;
  date: Date;
}

/* pack_users */
export interface PackUserRow {
  pack_id: number;
  user_id: number;
}

/* packs */
export interface PackRow {
  pack_id: number;
  name: string;
}

/* pending_relationships */
export interface PendingRelationshipRow {
  user1_id: number;
  user2_id: number;
  user1_choice: boolean;
  date: Date;
}

/* playdates */
export interface PlaydateRow {
  playdate_id: number;
  pack_id: number;
  user_id: number;
  body: string | null;
  start_date: Date;
  end_date: Date;
}

/* posts */
export interface PostRow {
  post_id: number;
  user_id: number;
  pack_id: number;
  body: string | null;
  date: Date;
  photo_url: string | null;
}

/* profile_photos */
export interface ProfilePhotoRow {
  photo_id: number;
  user_id: number;
  url: string;
}

/* schema_migrations */
export interface SchemaMigrationRow {
  name: string;
  applied_at: Date;
}

/* users */
export interface UserRow {
  user_id: number;
  dog_name: string | null;
  owner_name: string | null;
  dog_breed: string | null;
  age: number | null;
  vaccination: boolean;
  discoverable: boolean;
  owner_email: string;
  location: string | null;
  likes_one: string | null;
  likes_two: string | null;
  likes_three: string | null;
  is_guest: boolean;
  created_at: Date;
  demo_of: number | null;
  cloned_from: number | null;
  onboarded_at: Date | null;
  size: string | null;
  energy: string | null;
  best_time: string | null;
  bio: string | null;
}
